name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] <brief description>"
labels: enhancement
assignees:
  - Kent-Fulton

body:
  - type: markdown
    attributes:
      value: |
        Got an idea to improve the scripts? Let us know!

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      placeholder: e.g., Add logging to Restart-WSNM.ps1

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      placeholder: Describe the feature and its benefits.

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      placeholder: Explain how this feature would be used.
